/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DevotionalsRouteImport } from './routes/devotionals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachingsIdRouteImport } from './routes/teachings.$id'
import { Route as PodcastsIdRouteImport } from './routes/podcasts.$id'
import { Route as EssaysIdRouteImport } from './routes/essays.$id'
import { Route as DevotionalsIdRouteImport } from './routes/devotionals.$id'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalsRoute = DevotionalsRouteImport.update({
  id: '/devotionals',
  path: '/devotionals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsIdRoute = TeachingsIdRouteImport.update({
  id: '/teachings/$id',
  path: '/teachings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIdRoute = PodcastsIdRouteImport.update({
  id: '/podcasts/$id',
  path: '/podcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIdRoute = EssaysIdRouteImport.update({
  id: '/essays/$id',
  path: '/essays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalsIdRoute = DevotionalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevotionalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/devotionals': typeof DevotionalsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/devotionals': typeof DevotionalsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/devotionals': typeof DevotionalsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/devotionals'
    | '/explore'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/devotionals'
    | '/explore'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/devotionals'
    | '/explore'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DevotionalsRoute: typeof DevotionalsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  EssaysIdRoute: typeof EssaysIdRoute
  PodcastsIdRoute: typeof PodcastsIdRoute
  TeachingsIdRoute: typeof TeachingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotionals': {
      id: '/devotionals'
      path: '/devotionals'
      fullPath: '/devotionals'
      preLoaderRoute: typeof DevotionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/$id': {
      id: '/teachings/$id'
      path: '/teachings/$id'
      fullPath: '/teachings/$id'
      preLoaderRoute: typeof TeachingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$id': {
      id: '/podcasts/$id'
      path: '/podcasts/$id'
      fullPath: '/podcasts/$id'
      preLoaderRoute: typeof PodcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$id': {
      id: '/essays/$id'
      path: '/essays/$id'
      fullPath: '/essays/$id'
      preLoaderRoute: typeof EssaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotionals/$id': {
      id: '/devotionals/$id'
      path: '/$id'
      fullPath: '/devotionals/$id'
      preLoaderRoute: typeof DevotionalsIdRouteImport
      parentRoute: typeof DevotionalsRoute
    }
  }
}

interface DevotionalsRouteChildren {
  DevotionalsIdRoute: typeof DevotionalsIdRoute
}

const DevotionalsRouteChildren: DevotionalsRouteChildren = {
  DevotionalsIdRoute: DevotionalsIdRoute,
}

const DevotionalsRouteWithChildren = DevotionalsRoute._addFileChildren(
  DevotionalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DevotionalsRoute: DevotionalsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  EssaysIdRoute: EssaysIdRoute,
  PodcastsIdRoute: PodcastsIdRoute,
  TeachingsIdRoute: TeachingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
