/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DevotionalsRouteImport } from './routes/devotionals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevotionalsIndexRouteImport } from './routes/devotionals.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as TeachingsIdRouteImport } from './routes/teachings.$id'
import { Route as PodcastsIdRouteImport } from './routes/podcasts.$id'
import { Route as EssaysIdRouteImport } from './routes/essays.$id'
import { Route as DevotionalsIdRouteImport } from './routes/devotionals.$id'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as DevotionalsFocusIdRouteImport } from './routes/devotionals.focus.$id'
import { Route as DevotionalsSlugOverviewRouteImport } from './routes/devotionals.$slug.overview'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalsRoute = DevotionalsRouteImport.update({
  id: '/devotionals',
  path: '/devotionals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalsIndexRoute = DevotionalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevotionalsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsIdRoute = TeachingsIdRouteImport.update({
  id: '/teachings/$id',
  path: '/teachings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIdRoute = PodcastsIdRouteImport.update({
  id: '/podcasts/$id',
  path: '/podcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIdRoute = EssaysIdRouteImport.update({
  id: '/essays/$id',
  path: '/essays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalsIdRoute = DevotionalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevotionalsRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const DevotionalsFocusIdRoute = DevotionalsFocusIdRouteImport.update({
  id: '/focus/$id',
  path: '/focus/$id',
  getParentRoute: () => DevotionalsRoute,
} as any)
const DevotionalsSlugOverviewRoute = DevotionalsSlugOverviewRouteImport.update({
  id: '/$slug/overview',
  path: '/$slug/overview',
  getParentRoute: () => DevotionalsRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/devotionals': typeof DevotionalsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/new': typeof AdminNewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/devotionals/': typeof DevotionalsIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/devotionals/$slug/overview': typeof DevotionalsSlugOverviewRoute
  '/devotionals/focus/$id': typeof DevotionalsFocusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/new': typeof AdminNewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/devotionals': typeof DevotionalsIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/devotionals/$slug/overview': typeof DevotionalsSlugOverviewRoute
  '/devotionals/focus/$id': typeof DevotionalsFocusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/devotionals': typeof DevotionalsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/new': typeof AdminNewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/devotionals/$id': typeof DevotionalsIdRoute
  '/essays/$id': typeof EssaysIdRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/teachings/$id': typeof TeachingsIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/devotionals/': typeof DevotionalsIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/devotionals/$slug/overview': typeof DevotionalsSlugOverviewRoute
  '/devotionals/focus/$id': typeof DevotionalsFocusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/devotionals'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/saved'
    | '/admin/collections'
    | '/admin/content'
    | '/admin/invites'
    | '/admin/new'
    | '/collections/$slug'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
    | '/topics/$slug'
    | '/admin/'
    | '/devotionals/'
    | '/admin/collections/new'
    | '/admin/edit/$id'
    | '/devotionals/$slug/overview'
    | '/devotionals/focus/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/saved'
    | '/admin/collections'
    | '/admin/content'
    | '/admin/invites'
    | '/admin/new'
    | '/collections/$slug'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
    | '/topics/$slug'
    | '/admin'
    | '/devotionals'
    | '/admin/collections/new'
    | '/admin/edit/$id'
    | '/devotionals/$slug/overview'
    | '/devotionals/focus/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/devotionals'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/saved'
    | '/admin/collections'
    | '/admin/content'
    | '/admin/invites'
    | '/admin/new'
    | '/collections/$slug'
    | '/devotionals/$id'
    | '/essays/$id'
    | '/podcasts/$id'
    | '/teachings/$id'
    | '/topics/$slug'
    | '/admin/'
    | '/devotionals/'
    | '/admin/collections/new'
    | '/admin/edit/$id'
    | '/devotionals/$slug/overview'
    | '/devotionals/focus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DevotionalsRoute: typeof DevotionalsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EssaysIdRoute: typeof EssaysIdRoute
  PodcastsIdRoute: typeof PodcastsIdRoute
  TeachingsIdRoute: typeof TeachingsIdRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotionals': {
      id: '/devotionals'
      path: '/devotionals'
      fullPath: '/devotionals'
      preLoaderRoute: typeof DevotionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotionals/': {
      id: '/devotionals/'
      path: '/'
      fullPath: '/devotionals/'
      preLoaderRoute: typeof DevotionalsIndexRouteImport
      parentRoute: typeof DevotionalsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings/$id': {
      id: '/teachings/$id'
      path: '/teachings/$id'
      fullPath: '/teachings/$id'
      preLoaderRoute: typeof TeachingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$id': {
      id: '/podcasts/$id'
      path: '/podcasts/$id'
      fullPath: '/podcasts/$id'
      preLoaderRoute: typeof PodcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$id': {
      id: '/essays/$id'
      path: '/essays/$id'
      fullPath: '/essays/$id'
      preLoaderRoute: typeof EssaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotionals/$id': {
      id: '/devotionals/$id'
      path: '/$id'
      fullPath: '/devotionals/$id'
      preLoaderRoute: typeof DevotionalsIdRouteImport
      parentRoute: typeof DevotionalsRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/devotionals/focus/$id': {
      id: '/devotionals/focus/$id'
      path: '/focus/$id'
      fullPath: '/devotionals/focus/$id'
      preLoaderRoute: typeof DevotionalsFocusIdRouteImport
      parentRoute: typeof DevotionalsRoute
    }
    '/devotionals/$slug/overview': {
      id: '/devotionals/$slug/overview'
      path: '/$slug/overview'
      fullPath: '/devotionals/$slug/overview'
      preLoaderRoute: typeof DevotionalsSlugOverviewRouteImport
      parentRoute: typeof DevotionalsRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
  }
}

interface AdminCollectionsRouteChildren {
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminRouteChildren {
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DevotionalsRouteChildren {
  DevotionalsIdRoute: typeof DevotionalsIdRoute
  DevotionalsIndexRoute: typeof DevotionalsIndexRoute
  DevotionalsSlugOverviewRoute: typeof DevotionalsSlugOverviewRoute
  DevotionalsFocusIdRoute: typeof DevotionalsFocusIdRoute
}

const DevotionalsRouteChildren: DevotionalsRouteChildren = {
  DevotionalsIdRoute: DevotionalsIdRoute,
  DevotionalsIndexRoute: DevotionalsIndexRoute,
  DevotionalsSlugOverviewRoute: DevotionalsSlugOverviewRoute,
  DevotionalsFocusIdRoute: DevotionalsFocusIdRoute,
}

const DevotionalsRouteWithChildren = DevotionalsRoute._addFileChildren(
  DevotionalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DevotionalsRoute: DevotionalsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EssaysIdRoute: EssaysIdRoute,
  PodcastsIdRoute: PodcastsIdRoute,
  TeachingsIdRoute: TeachingsIdRoute,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
